my.greeting: Hello I am Amimul Ehsan

app.name: My app
app.desc: Welcome to ${app.name}

my.list.values: One,Two,Three

dbValues: "{connectionString: 'http://__', userName: 'foo' , password: 'pass' }"

db:
  host: blah
  port: 3367

#Nesting is the true power of YAML . (Yet another markup language)
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    active: test

  cloud:
    config:
      uri: http://localhost:8080

#  Default profile is always selected. And the another profile is placed at the top of it
# java -jar <Project Name> --spring.profiles.active=test
server:
  port: 8686
#  To make environment specific profiles